<?php

/**
 * Implementation of hook_feed_plugins().
 */
function feeds_oauth_feeds_plugins() {
  $info = array();
  $info['OAuth2HTTPSFetcher'] = array(
    'name' => 'Youtube authenticated feed',
    'description' => 'This feed uses authentication to pull in private feeds.',
    'help' => 'Uses clientLogin to authenticate requests to remote resources.',
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher', // This is the key name, not the class name.
      'class' => 'OAuth2HTTPSFetcher',
      'file' => 'OAuth2HTTPSFetcher.inc',
      'path' => drupal_get_path('module', 'feeds_oauth'),
    ),
  );
  return $info;
}

/**
 *  Implementation of hook_menu().
 */
function feeds_oauth_menu() {
  $items['feeds/oauth/authenticate'] = array(
    'title' => 'OAuth authentication',
    'type' => MENU_CALLBACK,
    'page callback' => 'feeds_oauth_authenticate',
    'access callback' => TRUE,
  );
  $items['feeds/oauth/callback'] = array(
    'title' => 'OAuth callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'feeds_oauth_callback',
    'access callback' => TRUE,
  );

  return $items;
}

function feeds_oauth_authenticate($id) {
  $fetcher = feeds_importer($id)->fetcher;
  $config = $fetcher->getConfig();

  $consumer = new DrupalOAuthConsumer($config['consumer_key'], $config['consumer_secret']);
  $oauth = new DrupalOAuthClient($consumer);

  // Set endpoint
  $_SESSION['feeds']['request_token_info'] = $oauth->getRequestToken($config['request_token_url']);
  $_SESSION['feeds']['id'] = $id;
  drupal_goto(url($config['authorize_url'], array('absolute' => TRUE, 'query' => array('oauth_token' => $_SESSION['feeds']['request_token_info']->key))));
}

function feeds_oauth_callback($site_id) {
  $fetcher = feeds_importer($_SESSION['feeds']['id'])->fetcher;
  $config = $fetcher->getConfig();
  $request_token = $_SESSION['feeds']['request_token_info'];

  $consumer = new DrupalOAuthConsumer($config['consumer_key'], $config['consumer_secret']);
  $oauth = new DrupalOAuthClient($consumer, $request_token);

  if ($_GET['oauth_token'] != $_SESSION['feeds']['request_token_info']->key) {
    drupal_set_message(t('Invalid OAuth token.'));
    drupal_goto('import/' . $site_id);
  }

  $access_token = $oauth->getAccessToken($config['access_token_url'], array('verifier' => $_GET['oauth_verifier']));
  global $user;
  db_merge('feeds_oauth_access_tokens')
    ->key(array('uid' => $user->uid, 'site_id' => $site_id))
    ->fields(array('uid' => $user->uid, 'site_id' => $site_id, 'oauth_token' => $access_token->key, 'oauth_token_secret' => $access_token->secret))
    ->execute();

  unset($_SESSION['feeds']);
  drupal_goto('import/' . $site_id);
}

/**
 * Implementation of hook_feeds_oauth_authenticator().
 */
function feeds_oauth_feeds_oauth_authenticator() {
  return array('feeds_oauth_get_tokens' => 'Feeds OAuth');
}
